protected/models/Payment.php
<?php

/**
 * This is the model class for table "tbl_payment".
 *
 * The followings are the available columns in table 'tbl_payment':
 * @property integer $id
 * @property integer $student_id
 * @property integer $course_id
 * @property integer $amount
 * @property string $date
 * @property integer $num
 * @property string $note
 *
 * The followings are the available model relations:
 * @property Student $student
 */
class Payment extends CActiveRecord
{
    /**
     * @return string the associated database table name
     */

    public $course_type_id;
    public $student_course_id;


    const FROM_INITIAL_PAYMENT = "مدفوع من الانتظار";

    public function tableName()
    {
        return 'tbl_payment';
    }

    public $num = 0;

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('student_id, course_id, amount, num,date', 'required', 'message' => 'الحقل " {attribute} " لايمكن ان يكون فارغا'),
            //array('student_id, course_id, amount, num', 'required', 'message' => 'الحقل " {attribute} " لايمكن ان يكون فارغا', 'on' => 'create'),
            array('date, num', 'required', 'message' => 'الحقل " {attribute} " لايمكن ان يكون فارغا','on'=>'update'),
            array('num','unique','on'=>'create'),
            array('student_id, course_id, amount, num', 'numerical', 'integerOnly' => true, 'message' => 'الحقل {attribute} يجب ان يكون رقما'),

            array('student_id', 'attendCourse'),
            array('amount', 'validAmount','on'=>'create'),
            array('note', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, student_id, course_id, amount, date, num, note', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'student' => array(self::BELONGS_TO, 'Student', 'student_id'),
            'course' => array(self::BELONGS_TO, 'Course', 'course_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'معرف الفاتورة',
            'student_course_id'=>'اسم الطالب',
            'student_id' => 'الطالب',
            'course_id' => 'اسم الدورة',
            'amount' => 'قيمة الفاتورة',
            'date' => 'تاريخ دفع الفاتورة',
            'num' => 'رقم الفاتورة',
            'note' => 'ملاحظات حول الفاتورة',
            'course_type_id' => 'الدورة',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('student_id', $this->student_id);
        $criteria->compare('course_id', $this->course_id);
        $criteria->compare('amount', $this->amount);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('num', $this->num);
        $criteria->compare('note', $this->note, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 20,
            ),
        ));


    }

    public function getLastPaymentNo($student_id, $course_id)
    {
        $command = Yii::app()->db->createCommand();
        $payments = $command->select('*')
            ->from('tbl_payment')
            ->where('student_id=:student_id AND course_id=:course_id', array(
                ':student_id' => $student_id,
                ':course_id' => $course_id,
            ))
            ->order('num DESC')
            ->queryAll();
        if (empty($payments)) {
            return 0;
        } else {
            return $payments[0]['num'];
        }
    }

    public function attendCourse($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $command = Yii::app()->db->createCommand();
            $rows = $command->select('*')
                ->from('tbl_student_course_assignment')
                ->where('student_id=:student_id AND course_id =:course_id', array(
                    ':student_id' => $this->student_id,
                    ':course_id' => $this->course_id,
                ))->queryAll();
            $status = !empty($rows);
            if (!$status) {
                $this->addError('student_id', 'الطالب غير موجود في الدورة');
            }
        }
    }
    public function validAmount($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $payments = Payment::model()->findAll("student_id=:student_id AND course_id=:course_id", array(
                ":student_id" => $this->student_id,
                "course_id" => $this->course_id,
            ));
            $course = Course::model()->findByPk($this->course_id);
            $courseCost = intval($course->getCostText());
            $paid = 0;
            foreach ($payments as $payment) {
                $paid += $payment->amount;
            }
            // Get the discount of the student ...
            $command = Yii::app()->db->createCommand();
            $assignments = $command->select('*')
                ->from('tbl_student_course_assignment')
                ->where('student_id = :student_id AND course_id = :course_id', array(
                    ':student_id' => $this->student_id,
                    ':course_id' => $this->course_id,
                ))
                ->queryAll();
            $assignment = $assignments[0];
            $discount =  $assignment['discount'];
            if($this->amount + $paid > $courseCost-$discount){
                $this->addError('amount', 'المبلغ اكبر من المطلوب');
            }
        }
    }


    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Payment the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }
}

protected/controllers/CourseController.php
<?php

include "BaseController.php";

class CourseController extends BaseController
{
    /**
     * This is a testing comment for upload
     *
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    public $main_section_title = "";

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'checkAccess',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */

    public function actionAttendanceList()
    {
        if (!isset($_GET['session_id'])) {
            throw new CHttpException(400);
        }
        $session_id = $_GET['session_id'];
        $session = Session::model()->findByPk($session_id);
        if ($session == null) {
            throw new CHttpException(404);
        }
        $this->pageTitle = "عرض حضور الطلاب";
        $this->layout = "//layouts/column2";
        $this->render('attendance_list', array(
            'session' => $session,
        ));
    }

    public function actionDeleteStudent()
    {
        $student = $this->loadStudentModel($_POST['sId']);
        $course = $this->loadModel($_POST['cId']);
        $command = Yii::app()->db->createCommand();
        $command->delete('tbl_payment', 'student_id=:student_id AND course_id=:course_id', array(
            ':student_id' => $student->id,
            ':course_id' => $course->id,
        ));
        $courseSessions = $course->sessions;
        $sessions_id = array();
        foreach ($courseSessions as $session) {
            $sessions_id[] = $session->id;
        }
        $command->reset();
        if (!empty($sessions_id)) {
            $command->delete('tbl_attendance', 'student_id=:student_id AND session_id in (' . implode(',', $sessions_id) . ')', array(
                ':student_id' => $student->id,
            ));
            $command->reset();
        }
        $command->delete('tbl_student_course_assignment', 'student_id=:student_id AND course_id=:course_id', array(
            ':student_id' => $student->id,
            ':course_id' => $course->id,
        ));
        echo CJSON::encode(array(
            'status' => true,
            'message' => 'تمت عملية حذف الطالب بنجاح',
        ));
    }

    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'alterCourseStatus'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('*'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->layout = "//layouts/column2";
        $course = $this->loadModel($id);
        $this->pageTitle = "لوحة التحكم الخاصة بدورة " . " " . $course->courseType->name;
        $studentDataProvider = new CActiveDataProvider('Student', array(
            'pagination' => array(
                'pageSize' => 10,
            ),
        ));
        // Get the students in the course
        $courseStudents = $course->students;
        foreach ($courseStudents as $student) {
            $student->course_id = $course->id;
        }
        // set Data Provider for course's students
        $studentDataProvider->setData($courseStudents);
        // Render Course (view) page
        $this->render('view', array(
            'model' => $course,
            'students' => $courseStudents,
            'studentDataProvider' => $studentDataProvider,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->pageTitle = "إنشاء دورة جديدة";
        $this->layout = "//layouts/column2";
        $courseType = CourseType::model()->findAll();

        if (empty($courseType)) {
            $this->redirect(array('courseType/create'));
        }

        $model = new Course('create');

        $instructorModel = new Instructor;
        if (isset($_GET['Instructor'])) {
            $instructorModel->attributes = $_GET['Instructor'];
        }
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        $model->status = Course::STATUS_NOT_YET_STARTED;
        $model->cost = 0;
        if (isset($_POST['Course'])) {
            $model->attributes = $_POST['Course'];
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
            'instructorModel' => $instructorModel,
        ));
    }

    public function actionDeleteSession($id)
    {
        $session_id = $id;
        $session = Session::model()->findByPk($session_id);
        $sessionNo = $session->num;
        foreach ($session->attendances as $attendance) {
            $attendance->delete();
        }
        if ($session->delete()) {
            echo CJSON::encode(array(
                'status' => true,
                'message' => "تم حذف الجلسة رقم: " . $sessionNo . " من نظام الدورات",
            ));
        } else {
            echo CJSON::encode(array(
                'status' => false,
                'message' => "لم يتمكن النظام من حذف الجلسة",
            ));
        }

    }

    public function actionShowStudentContract($student_id)
    {
        $this->layout = "//layouts/blank";
        $this->pageTitle = "بيان الاشتراك";
        $first_payment = 0;
        if (!empty($_GET['course_id'])) {
            $course_id = intval($_GET['course_id']);
            $course = $this->loadModel($course_id);
            $payments = Payment::model()->findAll('course_id=:course_id AND student_id=:student_id', array(
                ':course_id' => $course_id,
                ':student_id' => $student_id,
            ));
            $cost = $course->getCostText();

            $first_payment = empty($payments) ? null : $payments[0];
            if (!is_null($first_payment)) {
                $first_payment = $first_payment->amount;
            } else {
                $first_payment = 0;
            }

            $courseName = $course->courseType->name;
        } else if (!empty($_GET['course_type_id']) && !empty($_GET['cost']) && !empty($_GET['paid'])) {
            $courseName = CourseType::model()->findByPk(intval($_GET['course_type_id']))->name;
            $cost = $_GET['cost'];
            $first_payment = $_GET['paid'];
        } else {
            throw new CHttpException(400, 'طلب خاطئ');
        }
        $student_id = intval($_GET['student_id']);
        $student = $this->loadStudentModel($student_id);
        $telephoneNo = "لايوجد";
        $mobileNo = "لايوجد";
        $tels = $student->telNo;
        $mobs = $student->mobileNo;
        if (!empty($tels)) {
            $telephoneNo = $tels[0]->number;
        }
        if (!empty($mobs)) {
            $mobileNo = $mobs[0]->number;
        }

        $this->render('student_contract', array(
            'student' => $student,
            'courseName' => $courseName,
            'cost' => $cost,
            'telephoneNo' => $telephoneNo,
            'mobileNo' => $mobileNo,
            'first_payment' => $first_payment,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Course'])) {
            $model->attributes = $_POST['Course'];
            if ($model->save()) {
                echo CJSON::encode(array(
                    'success' => true,
                    'message' => 'The Course Has Been updated!',
                ));
            } else {
                echo CJSON::encode(array(
                    'success' => false,
                    'message' => 'There was an error!',
                ));
            }
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {

        if(isset($_POST['Course'])){
            $model = $this->loadModel(intval($_POST['Course']['id']));

            Yii::app()->db->createCommand()->delete('tbl_payment','course_id=:course_id',array(
                ':course_id'=>$model->id,
            ));
            Yii::app()->db->createCommand()->delete('tbl_student_course_assignment','course_id=:course_id',array(
                ':course_id'=>$model->id,
            ));
            Yii::app()->db->createCommand()->delete('tbl_session','course_id=:course_id',array(
                ':course_id'=>$model->id,
            ));
            Yii::app()->db->createCommand()->delete('tbl_damascus_list_entry','course_id=:course_id',array(
                ':course_id'=>$model->id,
            ));

protected/views/payment/_form.php
<?php
/**
 * Created by PhpStorm.
 * User: Burhan
 * Date: 1/16/2016
 * Time: 9:32 AM
 */

Yii::app()->clientScript->registerScript("course_script", '
$(function(){
    $(".ok-sign").hide();
    $(".error-sign").hide();

});
', CClientScript::POS_END);


?>
<div class="form">

    <?php $form = $this->beginWidget('CActiveForm', array(
        'id' => 'payment-add-form',
        'enableAjaxValidation' => false,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'successCssClass' => 'has-success',
            'errorCssClass' => 'has-error',
            'validatingErrorMessage' => '',
            'inputContainer' => '.form-group',
            'afterValidateAttribute' => 'js:function(form, attribute, data, hasError){
                $("#"+attribute.inputID).siblings(".error-sign").hide();
                $("#"+attribute.inputID).siblings(".ok-sign").hide();
                if(hasError){
                    $("#"+attribute.inputID).siblings(".error-sign").show();
                }else {
                    $("#"+attribute.inputID).siblings(".ok-sign").show();
                }
            }',
        ),
        'htmlOptions' => array(
            'role' => 'form',
            'class' => 'form-horizontal',
        ),
    )); ?>

    <?php if(strlen($message)>0):?>
        <div class="col-md-12">
            <div class="alert alert-success">
                <?php echo $message;?>
            </div>
        </div>
    <?php endif;?>
    <?php if($model->hasErrors()):?>
    <div class="col-md-12">
        <div class="alert alert-danger">
            <?php echo $form->errorSummary($model,'رجاء اصلح الأخطاء التالية');?>
        </div>
    </div>
    <?php endif;?>


    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'course_type_id', array('class' => 'col-md-2 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->dropDownList($model, 'course_type_id', CourseType::model()->getAvailableCourseTypes(), array(
                'prompt' => 'اختر نوع الدورة',
                'class' => 'form-control',
                'ajax' => array(
                    'url'=>Yii::app()->createUrl('payment/getStudentDropList'),
                    'data'=>array(
                        'course_type_id'=>'js:$(this).val()',
                    ),
                    'type'=>'GET',
                    'success'=>'js:function(data){
                        $("#students_drop_select").html(data);
                    }',
                    'beforeSend'=>'js:function(){
                        $("#students_drop_select").html("<option value=\"\">الرجاء الانتظار...</option>");
                    }',
                    'error'=>'js:function(){
                        $("#students_drop_select").html("");
                    }',
                ),

            )); ?>
            <?php echo $form->error($model, 'course_type_id'); ?>
        </div>
    </div>


    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'student_course_id', array('class' => 'col-md-2 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->dropDownList($model, 'student_course_id',array(), array(
                'prompt' => '',
                'class' => 'form-control',
                'id'=>'students_drop_select',
            )); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'student_course_id'); ?>
        </div>
    </div>

    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'amount', array('class' => 'col-md-2 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'amount', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'amount'); ?>
        </div>
    </div>
    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'num', array('class' => 'col-md-2 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'num', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'num'); ?>
        </div>
    </div>
    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'date', array('class' => 'col-md-2 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'date', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>

            <?php echo $form->error($model, 'date'); ?>
        </div>
    </div>
    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'note', array('class' => 'col-md-2 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'note', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>

            <?php echo $form->error($model, 'note'); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo CHtml::submitButton('دفع فاتورة', array(
                'class' => 'btn btn-danger',
            )); ?>
        </div>
    </div>


    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/payment/course_payments.php
<?php
/* @var $this PaymentController */

$this->breadcrumbs=array(
	'Payment'=>array('/payment'),
	'Course_payments',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

protected/views/payment/payments.php
<?php
/* @var $this PaymentController */
/* @var $dataProvider CActiveDataProvider */

// Create the Add a new Payment Modal ....
$model = new Payment;
$model->student_id = intval($_GET['sId']);
$model->course_id = intval($_GET['cId']);
$params = array(
    'form' => 'payment.add_form',
    'model' => $model,
    'title' => 'إضافة فاتورة جديدة',
    'modalName' => 'addNewPaymentModal',
);
$this->widget('application.components.Modal', $params);
// The end of the Add new Payment Modal

Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/vendor/vex.js", CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/vendor/vex.dialog.js", CClientScript::POS_END);

Yii::app()->clientScript->registerCSSFile(Yii::app()->baseUrl . "/css/vex/vex.css");
Yii::app()->clientScript->registerCSSFile(Yii::app()->baseUrl . "/css/vex/vex-theme-plain.css");
Yii::app()->clientScript->registerScript("refresh_payment_info", '
var refreshPaymentInfo = function(){
    $.ajax({
        "url":"' . $this->createUrl("getPaymentInfo", array("sId" => intval($_GET['sId']), "cId" => intval($_GET["cId"]))) . '",
        "dataType":"json",
        "success":function(data){
            $("#course_cost").html(data.cost);
            $("#course_cost_paid").html(data.paid);
            $("#course_cost_remaining").html(data.remaining);
            $("#discount_no").html(data.discount);
            $("#pleaseWait").modal("hide");
        },
        "beforeSend":function(xhr,setting){
            $("#pleaseWait .modal-body").html("الرجاء الانتظار");
            $("#pleaseWait").modal("show");
        }
    });
};
$(function(){
    $("#addDiscountLink").click(function(){
        $.ajax({
            "url":"'.$this->createUrl("addDiscount",array("sId" => intval($_GET['sId']), "cId" => intval($_GET["cId"]))).'",
            "success":function(data){
                $("#addDiscountModal .modal-body").html(data);
                $("#addDiscountModal").modal("show");
            }
        });
    });
});
refreshPaymentInfo();
', CClientScript::POS_END);

$this->options = array(
    array('name' => 'عرض سجل الطالب الشخصي', 'url' => Yii::app()->createUrl("student/view", array("id" => $this->_student->id)), 'id' => 'updateCourse', 'glyphicon' => 'glyphicon-user'),
    array('name' => 'عرض لوحة ادارة دورة ' . $this->_course->getCourseNameText(), 'url' => $this->createUrl('course/view', array('id' => $this->_course->id)), 'glyphicon' => 'glyphicon-list-alt'),
    array('name' => 'اضافة حسم' ,'url'=> "#",'id'=>"addDiscountLink", 'glyphicon' => 'glyphicon-usd'),

);

$this->widget('application.components.Ajaxmodal', array(
    'name' => 'paymentOptionsModal',
    'title' => 'خيارات فاتورة',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'paymentUpdateModal',
    'title' => 'تعديل بيانات فاتورة',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'pleaseWait',
    'title' => 'تحميل بيانات الدفع',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'addDiscountModal',
    'title' => 'اضافة حسم',
    'width' => '600px',
));
?>

<?php if ($dataProvider->totalItemCount == 0): ?>

    <p>لايوجد دفعات دفعها الطالب للدورة</p>
<?php endif; ?>

<div class="row">
    <div class="col-md-6">
        <h4>معلومات الطالب</h4>
        <hr style="border-color: #777;"/>
        <div class="row">
            <div class="col-md-6">الأسم الطالب</div>
            <div class="col-md-6"><span class="label-success label"><?php echo $this->_student->getName(); ?></span>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-6">رقم الدورة</div>
            <div class="col-md-6"><span class=" label label-success"><?php echo $this->_course->id; ?></span></div>
        </div>

        <br>

        <div class="row">
            <div class="col-md-6">اسم الدورة</div>
            <div class="col-md-6"><span
                    class=" label label-success"><?php echo $this->_course->getCourseNameText(); ?></span></div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-6">استاذ الدورة</div>
            <div class="col-md-6"><span
                    class=" label label-success"><?php echo $this->_course->instructor->getName(); ?></span></div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-6">تاريخ بداية الدورة</div>
            <div class="col-md-6"><span
                    class=" label label-success"><?php echo $this->_course->start_date; ?></span></div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-6">تاريخ نهاية الدورة</div>
            <div class="col-md-6"><span class=" label label-success"><?php echo $this->_course->end_date; ?></span>
            </div>
        </div>
        <br>
    </div>
    <div class="col-md-6">
        <h4>معلومات الدفعات</h4>
        <hr style="border-color: #777;"/>
        <div class="row">
            <div class="col-md-6">قيمة قسط الدورة</div>
            <div class="col-md-6">
                <span class="label label-warning" id="course_cost"></span>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-6">المدفوع</div>
            <div class="col-md-6">
                <span class="label label-success" id="course_cost_paid"></span>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-6">الخصم</div>
            <div class="col-md-6">
                <span class=" label label-danger" id="discount_no"></span>
            </div>
        </div>

        <hr style="border-color: #AAA;"/>
        <div class="row">
            <div class="col-md-6">المتبقي للدفع</div>
            <div class="col-md-6">
                <span class=" label label-danger" id="course_cost_remaining"></span>
            </div>
        </div>
        <br/>

    </div>
</div>
<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'app_grid',
    'afterAjaxUpdate' => 'js:function(id, data){
            $(".optionsButton").on("click",function(e){
                e.preventDefault();
                $.get( $(this).attr("href") ,{

                },
                function(data){
                    $("#paymentOptionsModal .modal-body").html(data);
                    $("#paymentOptionsModal").modal("show");
                }
                ,
                "html");
            });
        }',
    'dataProvider' => $dataProvider,
    'columns' => array(
        'num',
        'amount',
        'date',
        'note',
        array(
            'class' => 'CButtonColumn',
            'header' => 'خيارات الفواتير',
            'template' => '{options}',
            'buttons' => array(
                'options' => array(
                    'label' => 'خيارات',
                    'url' => 'Yii::app()->createUrl("payment/getPaymentOptions",array("id"=>$data->id))',
                    'options' => array(
                        'class' => 'btn btn-danger optionsButton',
                        'ajax' => array(
                            'url' => 'js:$(this).attr("href")',
                            'type' => 'GET',
                            'success' => 'js:function(data){
                                    $("#paymentOptionsModal .modal-body").html(data);
                            }',
                            'beforeSend' => 'js:function(xhr,setting){
                                    $("#paymentOptionsModal").modal("show");
                                    $("#paymentOptionsModal .modal-body").html("الرجاء الانتظار ...");

                            }',
                        ),
                    ),
                ),
            ),
        ),
    ),
)); ?>
<br/>
<br/>

<div class="row">
    <div class="col-md-4">
        <?php
        echo CHtml::link("إضافة فاتورة جديدة", '#', array(
            'class' => 'btn btn-danger btn-block',
            'data-toggle' => 'modal',
            'data-target' => "#addNewPaymentModal",
        ));
        ?>
    </div>
</div>