protected/controllers/IcdlController.php
<?php

include "BaseController.php";

class IcdlController extends BaseController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'postOnly + delete', // we only allow deletion via POST request
            'checkAccess',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
        if(Yii::app()->request->isAjaxRequest){
            $model=new ICDLCard('create');
            if(isset($_POST['ICDLCard']))
            {
                $model->attributes=$_POST['ICDLCard'];
                if($model->save()){
                    echo CJSON::encode(array(
                        'status'=>true,
                        'message'=>'تم إنشاء بطاقة ICDL جديدة بالرقم: '.$model->un_code,
                    ));
                }else{

                    echo CJSON::encode(array(
                        'status'=>false,
                        'message'=>$model->getErrors(),
                    ));
                }
            }else{
                throw new CHttpException(400);
            }
        }else{
            throw new CHttpException(400);
        }
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['ICDLCard']))
		{
            $model->setScenario('update');
			$model->attributes=$_POST['ICDLCard'];
			if($model->save()){
                echo CJSON::encode(array(
                    'status'=>true,
                    'message'=>'تم تعديل البطاقة ICDL: '.$model->un_code,
                ));
            }else{
                echo CJSON::encode(array(
                    'status'=>false,
                    'message'=>'فشل في تعديل البطاقة',
                ));
            }

		}


	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete()
	{
		if(isset($_POST['id'])){
            $ICDLCard = $this->loadModel(intval($_POST['id']));
            if($ICDLCard->delete()){
                echo CJSON::encode(array(
                   'status'=>true,
                   'message'=>'تم حذف بطاقة ال ICDL '.$ICDLCard->un_code,
                ));
            }else{
                echo CJSON::encode(array(
                    'status'=>false,
                    'message'=>'فشل في حذف بطاقة ال ICDL',
                ));
            }
        }else{
            throw new CHttpException(400);
        }
	}

    public function actionGetICDLCardDetails($id){
        $icdlCard = $this->loadModelWithTickets(intval($id));

        echo $this->renderPartial('partial/icdlCardDetails',array(
            'model'=>$icdlCard,
        ),false,true);
    }

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $this->pageTitle = "بطاقات ال ICDL";

		$ICDLCardModel=new ICDLCard('search');
        $ICDLCardModel->unsetAttributes();
        if(isset($_GET['ICDLCard'])){
            $ICDLCardModel->attributes = $_GET['ICDLCard'];
        }
		$this->render('index',array(
			'ICDLCardModel'=>$ICDLCardModel,
		));
	}

    public function actionExams(){
        $this->pageTitle = "امتحانات ال ICDL";
        $ICDLTicket = new ICDLTicket('search');
        $ICDLTicket->unsetAttributes();
        if(isset($_GET['ICDLTicket'])){
            $ICDLTicket->attributes = $_GET['ICDLTicket'];
        }

        $this->render('exams',array(
            'ICDLTicketModel'=>$ICDLTicket,
        ));
    }
    public function actionPrintExams(){
        $this->layout = "//layouts/blank";

        $this->pageTitle = "طباعة اسماء امتحان ICDL";
        $criteria = new CDbCriteria();

        if(isset($_GET['date'],$_GET['time'])){
            if(strlen($_GET['date'])>0 && strlen($_GET['time'])>0){
                $criteria->compare('date',$_GET['date']);
                $criteria->compare('time',$_GET['time']);
            }else{
                $this->redirect(array('icdl/exams','rel'=>'print-exam'));
            }
        }else{
            throw new CHttpException(400);
        }
        $ICDLTickets = ICDLTicket::model()->with('icdlCard')->findAll($criteria);
        $this->render('print_exams',array(
            'tickets'=>$ICDLTickets,
        ));

    }

    /**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new ICDLCard('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['ICDLCard']))
			$model->attributes=$_GET['ICDLCard'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=ICDLCard::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
    public function loadICDLTicketModel($id)
    {
        $model=ICDLTicket::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }
    public function loadModelWithTickets($id)
    {
        $model=ICDLCard::model()->with('tickets')->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    public function actionGetICDLCardCreateForm(){
        $ICDLCard = new ICDLCard('create');
        $ICDLCard->student_id = intval(130);
        echo $this->renderPartial('_form',array(
            'model'=>$ICDLCard,
        ),false,true);
    }

    public function actionGetICDLTicketCreateForm($id){
        $ICDLCard = $this->loadModel(intval($id));
        $model = new ICDLTicket('create');
        $model->icdl_card_id = $ICDLCard->id;
        echo $this->renderPartial('partial/icdl-ticket-form',array(
            'model'=>$model,
            'ICDLCard'=>$ICDLCard,
        ),false,true);
    }
    public function actionICDLTicketCreate(){
        if(Yii::app()->request->isAjaxRequest){
            if(isset($_POST['ICDLTicket'])){
                $model = new ICDLTicket('create');
                $model->attributes =$_POST['ICDLTicket'];
                if($model->save()){
                    echo CJSON::encode(array(
                        'status'=>true,
                        'message'=>'تم ادخال تذكرة امتحان بنجاح ',
                    ));
                }else{
                    echo CJSON::encode(array(
                        'status'=>false,
                        'message'=>'حدث خطأ عند ادخال تذكرة امحتان. تأكد من اكتمال ادخال البيانات',
                    ));
                }
            }else{
                throw new CHttpException(400);
            }
        }else{
            throw new CHttpException(400);
        }

    }

    public function actionGetICDLTicketUpdateForm($id){
        $ticketModel = $this->loadICDLTicketModel(intval($id));

        echo $this->renderPartial('partial/icdl-ticket-form',array(
            'model'=>$ticketModel,
            'ICDLCard'=>$ticketModel->icdlCard,
        ),false,true);
    }
    public function actionICDLTicketUpdate($id){

        if(isset($_POST['ICDLTicket'])){
            $model = $this->loadICDLTicketModel(intval($id));
            $model->setScenario('update');
            $model->attributes = $_POST['ICDLTicket'];
            if($model->save()){
                echo CJSON::encode(array(
                    'status'=>true,
                    'message'=>'تم تعديل بيانات التذكرة بنجاح',
                ));
            }else{
                echo CJSON::encode(array(
                    'status'=>false,
                    'message'=>'فشل في تعديل بيانات التذكرة. تأكد من اكتمال البيانات',
                ));
            }
        }else{
            throw new CHttpException(400);
        }
    }
    public function actionICDLTicketDelete()
    {
        if(isset($_POST['id'])){
            $model = $this->loadICDLTicketModel(intval($_POST['id']));
            if($model->delete()){
                echo CJSON::encode(array(
                    'status'=>true,
                    'message'=>'تم حذف التذكرة بنجاح',
                ));
            }else{
                echo CJSON::encode(array(
                    'status'=>false,
                    'message'=>'حدث خطأ عند حذف التذكرة',

protected/views/icdl/_exams_search.php
<?php
/**
 * Created by PhpStorm.
 * User: Dell 3521
 * Date: 17/05/15
 * Time: 06:13 م
 */

?>


<?php
/* @var $this IcdlController */
/* @var $model ICDLCard */
/* @var $form CActiveForm */
?>
<div class="panel panel-info">
    <div class="panel-heading">البحث في الامتحانات</div>
    <div class="panel-body">
        <?php $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
            'htmlOptions'=>array(
                'role'=>'form',
                'class'=>'form-horizontal',
            ),
        )); ?>

        <div class="form-group">
            <?php echo $form->label($model,'date',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'date',array('size'=>60,'maxlength'=>255,'id'=>'date-field','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group bootstrap-timepicker timepicker">
            <?php echo $form->label($model,'time',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'time',array('size'=>60,'maxlength'=>255,'id'=>'time-field','class'=>'form-control input-small')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <?php echo CHtml::submitButton('   فلترة   ',array(
                    'class'=>'btn btn-success',
                )); ?>
                <?php echo CHtml::button('   طباعة   ',array(
                    'class'=>'btn btn-warning',
                    'id'=>'print-btn',
                )); ?>
            </div>

        </div>

        <?php $this->endWidget(); ?>

    </div>

</div><!-- search-form -->

protected/views/icdl/_form.php
<?php
/* @var $this IcdlController */
/* @var $model ICDLCard */
/* @var $form CActiveForm */


Yii::app()->clientScript->registerScript("icdl_script", '
$(function(){
    $(".ok-sign").hide();
    $(".error-sign").hide();
});
', CClientScript::POS_END);
CommonFunctions::fixAjax();
?>

<div class="form">

    <?php $form = $this->beginWidget('CActiveForm', array(
        'id' => 'icdl-card-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation' => false,
        'enableClientValidation' => true,
        'focus' => array($model, 'first_names'),
        'clientOptions' => array(
            'successCssClass' => 'has-success',
            'errorCssClass' => 'has-error',
            'validatingErrorMessage' => '',
            'inputContainer' => '.form-group',
            'afterValidateAttribute' => 'js:function(form, attribute, data, hasError){
                $("#"+attribute.inputID).siblings(".error-sign").hide();
                $("#"+attribute.inputID).siblings(".ok-sign").hide();
                if(hasError){
                    $("#"+attribute.inputID).siblings(".error-sign").show();
                }else {
                    $("#"+attribute.inputID).siblings(".ok-sign").show();
                }
            }',
        ),
        'htmlOptions' => array(
            'role' => 'form',
            'class' => 'form-horizontal',
        ),
    )); ?>

    <br/>
    <div class="alert alert-info">
        <p class="note">الحقول بعلامة <span class="required">*</span> هي حقول مطلوبة</p>
    </div>

    <?php if ($model->hasErrors()): ?>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php echo $form->errorSummary($model, 'رجاء اصلح الأخطاء التالية:', $model->isNewRecord ? 'بعد الإصلاح اضغط إنشاء' : 'بعد الإصلاح اضغط تعديل') ?>
        </div>
    <?php endif; ?>

    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'first_name', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'first_name', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'first_name'); ?>
        </div>
        <?php echo $form->labelEx($model, 'last_name', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'last_name', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'last_name'); ?>
        </div>
    </div>
    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'first_name_en', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'first_name_en', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'first_name_en'); ?>
        </div>
        <?php echo $form->labelEx($model, 'last_name_en', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'last_name_en', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'last_name_en'); ?>
        </div>
    </div>

    <?php if(!$model->isNewRecord):?>
        <?php echo $form->hiddenField($model,'id');?>
    <?php endif;?>
    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'father_name', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'father_name', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'father_name'); ?>
        </div>
        <?php echo $form->labelEx($model, 'un_code', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'un_code', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'un_code'); ?>
        </div>
    </div>

    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'payment', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->textField($model, 'payment', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'payment'); ?>
        </div>
        <?php echo $form->labelEx($model, 'lang', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-3 input-container">
            <?php echo $form->dropDownList($model,'lang',array(
                ICDLCard::LANG_ARABIC=>'العربية',
                ICDLCard::LANG_ENGLISH=>'الإنكليزية',
            ),array(
                'class'=>'form-control',
                'prompt'=>'لغة الامتحان',
            )); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'payment'); ?>
        </div>
    </div>

       <?php echo $form->hiddenField($model, 'student_id'); ?>

    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8 col-md-offset-4 col-md-8">
            <?php echo CHtml::ajaxSubmitButton($model->isNewRecord?"إنشاء بطاقة جديدة":"تعديل البطاقة",$model->isNewRecord?Yii::app()->createUrl('icdl/create'):Yii::app()->createUrl('icdl/update',array('id'=>$model->id)),array(
                'type'=>'POST',
                'dataType'=>'json',
                'success'=>'js:function(data){
                    $("#createICDLCardModal .modal-body").html(data.message);
                    $("#updateICDLCardModal .modal-body").html(data.message);
                    if(data.status){
                        $.fn.yiiGridView.update("icdl-card-grid", {
                            data: $("#search-form-container form").serialize()
                        });
                    }
                }',
                'beforeSend'=>'js:function(){
                    $("#createICDLCardModal .modal-body").html("الرجاء الانتظار ...");
                    $("#updateICDLCardModal .modal-body").html("الرجاء الانتظار ...");
                }',
                'error'=>'js:function(){
                    $("#createICDLCardModal").modal("hide");
                    $("#updateICDLCardModal").modal("hide");
                }'
            ),array(
                'class'=>'btn btn-success',
                'id'=>'link-'.uniqid(),
            )); ?>
        </div>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/icdl/_search.php
<?php
/* @var $this IcdlController */
/* @var $model ICDLCard */
/* @var $form CActiveForm */
?>
<div class="panel panel-info">
    <div class="panel-heading">البحث في بطاقات ال ICDL</div>
    <div class="panel-body">
        <?php $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
            'htmlOptions'=>array(
                'role'=>'form',
                'class'=>'form-horizontal',
            ),
        )); ?>

        <div class="form-group">
            <?php echo $form->label($model,'first_name_en',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'first_name_en',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
            <?php echo $form->label($model,'last_name_en',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'last_name_en',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->label($model,'first_name',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
            <?php echo $form->label($model,'last_name',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>

        <div class="form-group">
            <?php echo $form->label($model,'un_code',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'un_code',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
            <?php echo $form->label($model,'father_name',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'father_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->label($model,'payment',array('class'=>'col-md-3','for'=>'name')); ?>
            <div class="col-md-3">
                <?php echo $form->textField($model,'payment',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>

        </div>


        <div class="form-group">
            <div class="col-md-offset-3 col-md-4">
                <?php echo CHtml::submitButton('   بحث   ',array(
                    'class'=>'btn btn-success',
                )); ?>
            </div>
        </div>

        <?php $this->endWidget(); ?>

    </div>

</div><!-- search-form -->

protected/views/icdl/index.php
<?php
/* @var $this IcdlController */
/* @var $dataProvider CActiveDataProvider */

$this->jsFiles[]= "icdl/_icdl.js";

$this->options = array(
    array(
        'id'=>'create-icdl-card-btn',
        'url'=>'#',
        'name'=>'إنشاء بطاقة جديدة',
        'glyphicon'=>'glyphicon glyphicon-floppy-saved',
    ),
    array(
        'id'=>'search-button',
        'url'=>'#',
        'name'=>'البحث في البطاقات',
        'glyphicon'=>'glyphicon glyphicon-search',
    ),
);
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'createICDLCardModal',
    'title' => 'إنشاء بطاقة ICDL',
    'width' => '60',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'createICDLTicketModal',
    'title' => 'إنشاء تذكرة ICDL',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'updateICDLTicketModal',
    'title' => 'تعديل بيانات تذكرة ICDL',
    'width' => '600px',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'updateICDLCardModal',
    'title' => 'تعديل بيانات بطاقة ICDL',
    'width' => '60',
));
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'pleaseWaitModal',
    'title' => 'معالجة',
    'width' => '600px',
));

Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/vendor/vex.js", CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/vendor/vex.dialog.js", CClientScript::POS_END);

Yii::app()->clientScript->registerCSSFile(Yii::app()->baseUrl . "/css/vex/vex.css");
Yii::app()->clientScript->registerCSSFile(Yii::app()->baseUrl . "/css/vex/vex-theme-plain.css");

Yii::app()->clientScript->registerScript('icdl-script','
$("#search-button").click(function(){
	$("#search-form-container").toggle();
	return false;
});
$("#search-form-container form").submit(function(){
        $.fn.yiiGridView.update("icdl-card-grid", {
            data: $(this).serialize()
        });
        return false;
    });
$(".Tabled table").addClass("table");
$(".Tabled table").addClass("subtable");
var getICDLCardCreateFormURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/getICDLCardCreateForm')).';
var ICDLCardDeleteURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/delete')).';
var getICDLCardUpdateFormURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/getICDLCardUpdateForm')).';
var getICDLCardDetailsURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/getICDLCardDetails')).';
var getICDLTicketCreateFormURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/getICDLTicketCreateForm')).';
var getICDLTicketUpdateFormURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/getICDLTicketUpdateForm')).';
var getTicketListURL = '.CJavaScript::encode(Yii::app()->createUrl('icdl/getTicketList')).';
var iCDLTicketDelete = '.CJavaScript::encode(Yii::app()->createUrl('icdl/iCDLTicketDelete')).';
',CClientScript::POS_END);

?>
<br/>
<div id="search-form-container" style="display:none">
    <?php $this->renderPartial('_search',array(
        'model'=>$ICDLCardModel,
    )); ?>
</div><!-- search-form -->
<div id="icdl-card-detail-container">

</div>
<br/>
<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'icdl-card-grid',
    'summaryText' => '',
    'afterAjaxUpdate' => 'js:function(){
            $("#filterPleaseWaitModal").modal("hide");
        	$(".Tabled table").addClass("table");
            $(".Tabled table").addClass("subtable");
            updateICDLCardList();
         }',
    'htmlOptions' => array(
        'class' => 'Tabled',
    ),
    'showTableOnEmpty'=>false,
    'emptyText'=>'لايوجد نتائج',
    'cssFile' => Yii::app()->baseUrl . '/css/main.css',
    'dataProvider' => $ICDLCardModel->search(),
    'columns' => array(
        array(
            'header'=>'الاسم بالانكليزي',
            'value'=>'$data->first_name_en." ".$data->last_name_en',
        ),
        array(
            'header'=>'الاسم بالعربي',
            'value'=>'$data->first_name." ".$data->last_name',
        ),
        'un_code',
        'payment',
        array(
            'name'=>'اللغة',
            'value'=>'$data->getLanguageText()',
        ),
        array(
            'header'=>'خيارات',
            'value'=>array($this,'renderICDLCardOptions'),
        ),
    )
)); ?>