protected/controllers/StudentController.php
<?php

include "BaseController.php";

class StudentController extends BaseController
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    public $_student;
    public $main_section_title;
    public $_course;

    public $_course_type_id;
    public $_registration = array();

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'studentContext + register,payments,getRegisterForWaitForm', // To enforce the student context when asking for the listed actions
            'courseContext +payments', // To enforce the course context when asking for the listed actions
            'checkAccess',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */

    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'register', 'RetrieveWaitingList', 'Waitinglist', 'create', 'update', 'payments'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }


    public function actionGetPrintContractForm($sId)
    {
        $student = $this->loadModel($sId);
        if (empty($_GET['course_type_id'])) {
            throw new CHttpException(400);
        }
        $this->renderPartial('print-contract-form', array('student' => $student, 'course_type_id' => $_GET['course_type_id']));
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->pageTitle = 'لوحة ادارة طالب';
        $studentModel = $this->loadModel($id);

        $courseDataProvider = new CActiveDataProvider('Course');
        $courses = $studentModel->courses;
        foreach ($courses as $course) {
            $course->student_id = $studentModel->id;
        }
        $courseDataProvider->setData($courses);

        $this->render('view', array(
            'model' => $studentModel,
            'courseDataProvider' => $courseDataProvider,
            'onWaitRegistrations' => $studentModel->registrations,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $this->pageTitle = "تسجيل طالب جديد";
        $this->layout = '//layouts/column2';
        $studentModel = new Student('create');
        $phoneNoModel = new PhoneNumber('create');
        $mobileNoModel = new PhoneNumber('create');
        $mobileNoModel->setScenario('mobile_no');
        $phoneNoModelExtra = new PhoneNumber('create');
        $mobileNoModelExtra = new PhoneNumber('create');
        $mobileNoModelExtra->setScenario('mobile_no');
        $registrationModel = new Registration;
        $message = "";
        if (isset($_POST['Student'])) {
            //$student = Student::model()->find('national_no=:national_no', array(
            //  ':national_no' => $_POST['Student']['national_no'],
            //));
            //if ($student == null) {
            $studentModel->attributes = $_POST['Student'];
            $registrationModel->attributes = $_POST['Registration'];
            $valid = $studentModel->validate() && $registrationModel->course_type_id > 0;
            if ($valid) {
                $father_name = $studentModel->father_name;
                $first_name = $studentModel->first_name;
                $last_name = $studentModel->last_name;
                $queryStudent = Student::model()->find('first_name=:first_name AND last_name=:last_name AND father_name=:father_name', array(
                    ':first_name' => $first_name,
                    ':last_name' => $last_name,
                    ':father_name' => $father_name,
                ));
                if ($queryStudent == null) {
                    $studentModel->save(false);
                    $registrationModel->student_id = $studentModel->id;
                    $registrationModel->status = Student::STATUS_WAITING;
                    $registrationModel->registration_date = date('Y-m-d');
                    $registrationModel->save();

                    //Phone Number Model
                    $phoneNoModel->number = $_POST['PhoneNumber'][1]['number'];
                    $phoneNoModel->type = PhoneNumber::HOME_NUMBER;
                    $phoneNoModel->owner_id = $studentModel->id;
                    $phoneNoModel->save();
                    $phoneNoModelExtra->number = $_POST['PhoneNumber'][3]['number'];
                    $phoneNoModelExtra->type = PhoneNumber::HOME_NUMBER;
                    $phoneNoModelExtra->owner_id = $studentModel->id;
                    $phoneNoModelExtra->save();

                    //Mobile Number Model
                    $mobileNoModel->number = $_POST['PhoneNumber'][2]['number'];
                    $mobileNoModel->type = PhoneNumber::MOBILE_NUMBER;
                    $mobileNoModel->owner_id = $studentModel->id;
                    $mobileNoModel->save();
                    $mobileNoModelExtra->number = $_POST['PhoneNumber'][4]['number'];
                    $mobileNoModelExtra->type = PhoneNumber::MOBILE_NUMBER;
                    $mobileNoModelExtra->owner_id = $studentModel->id;
                    $mobileNoModelExtra->save();

                    $link = CHtml::link($studentModel->first_name . " " . $studentModel->last_name,
                        $this->createUrl('view', array(
                            'id' => $studentModel->id
                        )));
                    $message = "تم تسجيل الطالب بنجاح " . $link;
                } else {
                    $link = CHtml::link($queryStudent->first_name . " " . $queryStudent->last_name,
                        $this->createUrl('view', array(
                            'id' => $queryStudent->id
                        )));
                    $message = " الطالب " . $link . " موجود مسبقا";
                }
                $studentModel = new Student('create');
                $phoneNoModel = new PhoneNumber('create');
                $mobileNoModel = new PhoneNumber('create');
                $registrationModel = new Registration;
                $phoneNoModelExtra = new PhoneNumber('create');
                $mobileNoModelExtra = new PhoneNumber('create');
            }
            //}
        }
        $phoneNoModel->clearErrors();
        $mobileNoModel->clearErrors();
        $phoneNoModelExtra->clearErrors();
        $mobileNoModelExtra->clearErrors();
        $mobileNoModelExtra->setScenario('mobile_no');
        $mobileNoModel->setScenario('mobile_no');
        $this->render('create', array(
            'registrationModel' => $registrationModel,
            'studentModel' => $studentModel,
            'phoneNoModel' => $phoneNoModel,
            'mobileNoModel' => $mobileNoModel,
            'phoneNoModelExtra' => $phoneNoModelExtra,
            'mobileNoModelExtra' => $mobileNoModelExtra,
            'message' => $message,
        ));
    }

    public function actionViewContactInfo($ids, $ctid)
    {
        $this->layout = "//layouts/blank";
        $this->pageTitle = "بيانات الاتصال";
        $criteria = new CDbCriteria;
        $criteria->compare('student_id', explode(',', $ids));
        $criteria->compare('course_type_id', $ctid);
        $registrations = Registration::model()->findAll($criteria);
        $this->render("view_contact_info", array(
            'registrations' => $registrations,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $this->layout = '//layouts/column2';
        $model = $this->loadModel($id);

        if (count($model->telNo) > 0) {
            $phoneNoModel = $model->telNo[0];
            if (count($model->telNo) > 1) {
                $phoneNoModelExtra = $model->telNo[1];
            } else {
                $phoneNoModelExtra = new PhoneNumber('create');
            }
        } else {
            $phoneNoModelExtra = new PhoneNumber('create');
            $phoneNoModel = new PhoneNumber('create');
        }
        if (count($model->mobileNo) > 0) {
            $mobileNoModel = $model->mobileNo[0];
            if (count($model->mobileNo) > 1) {
                $mobileNoModelExtra = $model->mobileNo[1];
            } else {
                $mobileNoModelExtra = new PhoneNumber('create');
            }
        } else {
            $mobileNoModelExtra = new PhoneNumber('create');
            $mobileNoModel = new PhoneNumber('create');
        }
        $mobileNoModelExtra->setScenario('mobile_no');
        $mobileNoModel->setScenario('mobile_no');
        $message = "";
        $this->pageTitle = "تعديل بيانات الطالب " . $model->first_name . " " . $model->last_name;
        if (isset($_GET['ajax_validate'])) {
            $this->performAjaxValidation($model);
            Yii::app()->end();
        }
        if (isset($_POST['Student'])) {
            $model->attributes = $_POST['Student'];
            if ($model->save()) {
                if (strlen($_POST['PhoneNumber'][1]['number']) > 0) {
                    $phoneNoModel->number = $_POST['PhoneNumber'][1]['number'];
                    if ($phoneNoModel->isNewRecord) {
                        $phoneNoModel->owner_id = $model->id;
                        $phoneNoModel->type = PhoneNumber::HOME_NUMBER;
                    }

protected/views/student/_search.php
<?php
/* @var $this StudentController */
/* @var $model Student */
/* @var $form CActiveForm */
?>

<div class="panel panel-info">
    <div class="panel-heading">البحث المتقدم في الطلاب</div>
    <div class="panel-body">
        <?php $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
            'htmlOptions'=>array(
                'role'=>'form',
                'class'=>'form-horizontal',
            ),
        )); ?>

        <div class="form-group">
            <?php echo $form->label($model,'first_name',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->label($model,'last_name',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->label($model,'national_no',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'national_no',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->label($model,'father_name',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'father_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->label($model,'mother_name',array('class'=>'col-md-2','for'=>'name')); ?>
            <div class="col-md-4">
                <?php echo $form->textField($model,'mother_name',array('size'=>60,'maxlength'=>255,'id'=>'name','class'=>'form-control')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <?php echo CHtml::submitButton('   فلترة   ',array(
                    'class'=>'btn btn-success',
                )); ?>
            </div>
        </div>

        <?php $this->endWidget(); ?>

    </div>

</div><!-- search-form -->

protected/views/student/_view.php
<?php
/* @var $this StudentController */
/* @var $data Student */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('first_name')); ?>:</b>
	<?php echo CHtml::encode($data->first_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_name')); ?>:</b>
	<?php echo CHtml::encode($data->last_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('father_name')); ?>:</b>
	<?php echo CHtml::encode($data->father_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mother_name')); ?>:</b>
	<?php echo CHtml::encode($data->mother_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nationality')); ?>:</b>
	<?php echo CHtml::encode($data->nationality); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('qualification')); ?>:</b>
	<?php echo CHtml::encode($data->qualification); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('residency')); ?>:</b>
	<?php echo CHtml::encode($data->residency); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('occupation')); ?>:</b>
	<?php echo CHtml::encode($data->occupation); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('national_no')); ?>:</b>
	<?php echo CHtml::encode($data->national_no); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('img_src')); ?>:</b>
	<?php echo CHtml::encode($data->img_src); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('how_to_know_us')); ?>:</b>
	<?php echo CHtml::encode($data->how_to_know_us); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('DOB')); ?>:</b>
	<?php echo CHtml::encode($data->DOB); ?>
	<br />

	*/ ?>

</div>

protected/views/student/admin.php
<?php
/* @var $this StudentController */
/* @var $model Student */

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#student-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Students</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'student-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(

		'first_name',
		'last_name',
		'father_name',
		'mother_name',
		'nationality',
		/*
		'qualification',
		'residency',
		'occupation',
		'national_no',
		'img_src',
		'how_to_know_us',
		'DOB',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/student/create.php
<?php
/* @var $this StudentController */
/* @var $studentModel Student */
/* @var $phoneNoModel PhoneNumber */

$this->options = array(
    array('name' => 'العودة الى صفحة ادارة الطلاب', 'url' => $this->createUrl('student/index'), 'active' => true, 'glyphicon' => 'glyphicon-share-alt'),

);

Yii::app()->clientScript->registerScript("course_script",'
$(function(){
    $(".ok-sign").hide();
    $(".error-sign").hide();
});
',CClientScript::POS_END);

?>
<br/>
<?php $this->renderPartial('_form', array(
    'studentModel'=>$studentModel,
    'phoneNoModel'=>$phoneNoModel,
    'registrationModel' => $registrationModel,
    'mobileNoModel' => $mobileNoModel,
    'phoneNoModelExtra' => $phoneNoModelExtra,
    'mobileNoModelExtra'=> $mobileNoModelExtra,
    'message'=>$message,
)); ?>

protected/views/student/index.php
<?php
/* @var $model Student */
/* @var $this StudentController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    array(
        'name'=>'الرئيسية',
        'url'=>$this->createUrl("site/index"),
    ),
    'الطلاب',
);

Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/vendor/vex.js", CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . "/js/vendor/vex.dialog.js", CClientScript::POS_END);

Yii::app()->clientScript->registerCSSFile(Yii::app()->baseUrl . "/css/vex/vex.css");
Yii::app()->clientScript->registerCSSFile(Yii::app()->baseUrl . "/css/vex/vex-theme-plain.css");

$this->options=array(
    array('name'=>'البحث عن الطلاب', 'url'=>"#",'id'=>'search-button','glyphicon'=>'glyphicon-search'),
    array('name'=>'إنشاء طالب جديد', 'url'=>$this->createUrl('student/create'),'glyphicon'=>'glyphicon-pencil'),
    array('name'=>'لوائح الانتظار', 'url'=>$this->createUrl('student/waitingList'),'glyphicon'=>'glyphicon-list-alt'),
);
Yii::app()->clientScript->registerScript('search', "
$(function(){
       //var pagerContainer = $('.pager');
       //$('.pager ul').removeClass('yiiPager').addClass('pagination');
       //pagerContainer.removeClass('pager');
       /* $('.pagination a').click(function(e){
            e.preventDefault();
        });*/
        $('.search-form form').submit(function(){
            $('#app_grid').yiiGridView('update', {
                data: $(this).serialize()
            });
            return false;
        });
        $('.Tabled table').addClass('table');
        $('.Tabled table').addClass('subtable');
});
var slide = 0;
$('#search-button').click(function(){
    if(slide == 0){
        $('.search-form').slideDown();
        slide =1;
    }else {
        $('.search-form').slideUp();
        slide =0;
    }
	return false;
});");
$this->widget('application.components.Ajaxmodal', array(
    'name' => 'payModal',
    'title' => 'دفع فاتورة',
    'width' => '70',
));
?>
<br/>
<div class="search-form">
    <?php $this->renderPartial('_search',array(
        'model'=>$model,
    )); ?>
</div><!-- search-form -->



<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'app_grid',
    'summaryText'=>'',
    'showTableOnEmpty'=>false,
    'emptyText'=>'ابحث ضمن الطلاب',
    'afterAjaxUpdate'=>'js:function(){
        	$(".Tabled table").addClass("table");
            $(".Tabled table").addClass("subtable");
           /* var pagerContainer = $(".pager");
        $(".pager ul").removeClass("yiiPager").addClass("pagination");
        $(".pagination a").click(function(e){
            e.preventDefault();
        });
        pagerContainer.removeClass("pager");*/


         }',
    'htmlOptions'=>array(
        'class'=>'Tabled',
    ),
    /*'pager'=>array(
        'class'=>'CLinkPager',
        'internalPageCssClass'=>null,
        'hiddenPageCssClass'=>'hidden',
        'prevPageLabel'=>'السابق',
        'previousPageCssClass'=>'next',
        'firstPageLabel'=>'الأول',
        'firstPageCssClass'=>'first',
        'lastPageCssClass'=>'last',
        'lastPageLabel'=>'الأخير',
        'maxButtonCount'=>6,
        'header'=>'',
        'nextPageLabel'=>'التالي',
        'nextPageCssClass'=>'previous',
    ),*/
    'cssFile'=>Yii::app()->baseUrl.'/css/main.css',
	'dataProvider'=>$model->search(),
	'columns'=>array(
        array(
            'header'=>'معرف',
            'name'=>'id',
            'filter'=>false,
            // 'filter'=>CHtml::dropDownList('id','0',CHtml::listData($model->findAll(),'id','first_name')),
            // Note That It's HTML ....
        ),
        array(
            'header'=>'الأسم الأول',
            'name'=>'first_name',
        ),
        array(
            'header'=>'الأسم الأخير',
            'name'=>'last_name',
        ),
        array(
            'header'=>'حالة البيانات',
            'value'=>array($this,'renderInfoCompletenessStatusForStudentListing'),
        ),
        'national_no',
        'father_name',
        'mother_name',
        /*array(
            'header'=>'رقم الخليوي',
            'value'=>'!empty($data->mobileNo(array("limit"=>1)))?$data->mobileNo(array("limit"=>1))[0]->number:"----------"',
        ),
        array(
            'header'=>'رقم الأرضي',
            'value'=>'!empty($data->telNo(array("limit"=>1)))?$data->telNo(array("limit"=>1))[0]->number:"----------"',
        ),*/
        array(
            'header' => 'دفع فاتورة',
            'class' => 'CButtonColumn',
            'template' => '{options}',
            'buttons' => array(
                'options' => array(
                    'label' => '<span class="glyphicon glyphicon-usd"></span>',
                    'click' => 'js:function(event){
                        var ajaxUrl = $(this).attr("href");
                        $.ajax({
                          "url":ajaxUrl,
                          "type":"GET",
                          "success":function(data){
                                $("#payModal .modal-body").html(data);
                          },
                          "beforeSend":function(){
                                $("#payModal .modal-body").html("الرجاء الانتظار");
                                $("#payModal").modal("show");
                          }
                        });
                        return false;
                    }',
                    'url' => 'Yii::app()->createUrl("payment/getPaymentForm",array("sId"=>$data->id,"ref"=>"student_page"))',
                    'options' => array(
                        'style'=>'color:#222;font-size:21px;',
                        'id'=>'link-'.uniqid(),
                    ),
                )
            )
        ),

        array(
            'type'=>'raw',
            'header'=>'عرض',
            'value'=>array($this,'renderViewLink'),
        ),
        array(
            'type'=>'raw',
            'header'=>'تعديل',
            'value'=>array($this,'renderUpdateLink'),
        ),
    ),
)); ?>

protected/views/student/print-contract-form.php
<?php
/**
 * Created by PhpStorm.
 * User: Burhan
 * Date: 1/16/2016
 * Time: 3:20 PM
 */
?>



<form role="form" class="form-horizontal" method="get" action="<?php echo Yii::app()->createUrl("course/showStudentContract");?>">
    <div class="row">
        <div class="col-md-12"><!-- right column container container -->
            <?php echo CHtml::hiddenField('student_id',$student->id)?>
            <?php echo CHtml::hiddenField('course_type_id',$course_type_id)?>
            <div class="form-group has-feedback">
                <?php echo CHtml::label("الدورة", "course", array('class' => 'col-md-4')); ?>
                <div class="col-md-8 input-container">
                    <span><?php echo CourseType::model()->findByPk($course_type_id)->name;?></span>
                </div>
            </div>
            <div class="form-group has-feedback">
                <?php echo CHtml::label("قسط الدورة", "cost", array('class' => 'col-md-4')); ?>
                <div class="col-md-8 input-container">
                    <input type="text" id="cost" name="cost" class="form-control">
                </div>
            </div>
            <div class="form-group has-feedback">
                <?php echo CHtml::label("المدفوع", "paid", array('class' => 'col-md-4')); ?>
                <div class="col-md-8 input-container">
                    <input type="text" id="paid" name="paid" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <?php echo CHtml::submitButton('البيان') ?>
                </div>
            </div>
        </div>

    </div>
</form>

protected/views/student/update.php
<?php
/* @var $this StudentController */
/* @var $model Student */

$this->options = array(
    array('name' => 'العودة الى صفحة ادارة الطلاب', 'url' => $this->createUrl('student/index'), 'active' => true, 'glyphicon' => 'glyphicon-share-alt'),
    array('name' => 'العودة الى صفحة الطالب', 'url' => $this->createUrl('student/view', array('id' => $model->id)), 'active' => true, 'glyphicon' => 'glyphicon-user'),

);

Yii::app()->clientScript->registerScript("course_script", '
$(function(){
    $(".ok-sign").hide();
    $(".error-sign").hide();
});
', CClientScript::POS_END);

?>
    <br/>
<?php $this->renderPartial('_form', array('studentModel' => $model, 'phoneNoModel' => $phoneNoModel, 'mobileNoModel' => $mobileNoModel, 'phoneNoModelExtra' => $phoneNoModelExtra,
    'mobileNoModelExtra' => $mobileNoModelExtra, 'message' => $message)); ?>

protected/views/student/view_contact_info.php
<?php
/**
 * @var $registrations Registration[]
 */
?>

<?php if (empty($registrations)): ?>
    لايوجد طلاب للعرض
<?php endif; ?>
<?php if (!empty($registrations)): ?>
    <div class="row">
        <div class="col-md-6">
            <table class="table table-bordered">
                <tr>
                    <th>اسم الطالب</th>
                    <th>الهاتف الأرضي</th>
                    <th>الهاتف الخلوي</th>
                    <th>ملاحظات</th>
                </tr>
                <?php foreach ($registrations as $registration): ?>
                    <tr>
                        <?php $student = Student::model()->find('id=:id',array(':id'=>$registration->student_id));?>
                        <td><?php echo $student->getName(); ?></td>
                        <td><?php $numberTel = $student->telNo;
                            echo !empty($numberTel) ? $numberTel[0]->number : ""; ?></td>
                        <td><?php $numberMobile = $student->mobileNo;
                            echo !empty($numberMobile) ? $numberMobile[0]->number : ""; ?></td>
                        <td><?php echo $registration->note;?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>

<?php endif; ?>

protected/views/student/waiting_list_summary.php
<?php
/**
 * Created by PhpStorm.
 * User: Dell 3521
 * Date: 16/07/14
 * Time: 04:48 م
 */
?>
<?php if (empty($summaryData)): ?>
    <p>لايوجد اي اسم في لوائح الانتظار</p>
<?php endif; ?>
<?php if (!empty($summaryData)): ?>
    <table class="table subtable">
        <thead>
        <tr>
            <th>اسم الدورة</th>
            <th>عدد الطلاب المنتظرين</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($summaryData as $data): ?>
            <tr>
                <td><?php echo $data['name'] ?></td>
                <td><?php echo $data['count'] ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

<?php endif; ?>