protected/models/Payment.php
<?php

/**
 * This is the model class for table "tbl_payment".
 *
 * The followings are the available columns in table 'tbl_payment':
 * @property integer $id
 * @property integer $student_id
 * @property integer $course_id
 * @property integer $amount
 * @property string $date
 * @property integer $num
 * @property string $note
 *
 * The followings are the available model relations:
 * @property Student $student
 */
class Payment extends CActiveRecord
{
    /**
     * @return string the associated database table name
     */

    public $course_type_id;
    public $student_course_id;


    const FROM_INITIAL_PAYMENT = "مدفوع من الانتظار";

    public function tableName()
    {
        return 'tbl_payment';
    }

    public $num = 0;

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('student_id, course_id, amount, num,date', 'required', 'message' => 'الحقل " {attribute} " لايمكن ان يكون فارغا'),
            //array('student_id, course_id, amount, num', 'required', 'message' => 'الحقل " {attribute} " لايمكن ان يكون فارغا', 'on' => 'create'),
            array('date, num', 'required', 'message' => 'الحقل " {attribute} " لايمكن ان يكون فارغا','on'=>'update'),
            array('num','unique','on'=>'create'),
            array('student_id, course_id, amount, num', 'numerical', 'integerOnly' => true, 'message' => 'الحقل {attribute} يجب ان يكون رقما'),

            array('student_id', 'attendCourse'),
            array('amount', 'validAmount','on'=>'create'),
            array('note', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, student_id, course_id, amount, date, num, note', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'student' => array(self::BELONGS_TO, 'Student', 'student_id'),
            'course' => array(self::BELONGS_TO, 'Course', 'course_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'معرف الفاتورة',
            'student_course_id'=>'اسم الطالب',
            'student_id' => 'الطالب',
            'course_id' => 'اسم الدورة',
            'amount' => 'قيمة الفاتورة',
            'date' => 'تاريخ دفع الفاتورة',
            'num' => 'رقم الفاتورة',
            'note' => 'ملاحظات حول الفاتورة',
            'course_type_id' => 'الدورة',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('student_id', $this->student_id);
        $criteria->compare('course_id', $this->course_id);
        $criteria->compare('amount', $this->amount);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('num', $this->num);
        $criteria->compare('note', $this->note, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 20,
            ),
        ));


    }

    public function getLastPaymentNo($student_id, $course_id)
    {
        $command = Yii::app()->db->createCommand();
        $payments = $command->select('*')
            ->from('tbl_payment')
            ->where('student_id=:student_id AND course_id=:course_id', array(
                ':student_id' => $student_id,
                ':course_id' => $course_id,
            ))
            ->order('num DESC')
            ->queryAll();
        if (empty($payments)) {
            return 0;
        } else {
            return $payments[0]['num'];
        }
    }

    public function attendCourse($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $command = Yii::app()->db->createCommand();
            $rows = $command->select('*')
                ->from('tbl_student_course_assignment')
                ->where('student_id=:student_id AND course_id =:course_id', array(
                    ':student_id' => $this->student_id,
                    ':course_id' => $this->course_id,
                ))->queryAll();
            $status = !empty($rows);
            if (!$status) {
                $this->addError('student_id', 'الطالب غير موجود في الدورة');
            }
        }
    }
    public function validAmount($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $payments = Payment::model()->findAll("student_id=:student_id AND course_id=:course_id", array(
                ":student_id" => $this->student_id,
                "course_id" => $this->course_id,
            ));
            $course = Course::model()->findByPk($this->course_id);
            $courseCost = intval($course->getCostText());
            $paid = 0;
            foreach ($payments as $payment) {
                $paid += $payment->amount;
            }
            // Get the discount of the student ...
            $command = Yii::app()->db->createCommand();
            $assignments = $command->select('*')
                ->from('tbl_student_course_assignment')
                ->where('student_id = :student_id AND course_id = :course_id', array(
                    ':student_id' => $this->student_id,
                    ':course_id' => $this->course_id,
                ))
                ->queryAll();
            $assignment = $assignments[0];
            $discount =  $assignment['discount'];
            if($this->amount + $paid > $courseCost-$discount){
                $this->addError('amount', 'المبلغ اكبر من المطلوب');
            }
        }
    }


    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Payment the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }
}

protected/controllers/PaymentController.php
<?php

include "BaseController.php";

class PaymentController extends BaseController
{

    public $_student;
    public $_course;

    const EXTRA_PAYMENT_OPTIONS_TOKEN = 1;

    public function filters()
    {
        return array(
            'postOnly + delete', // we only allow deletion via POST request
            'studentContext +payments,addDiscount',
            'courseContext +payments,addDiscount',
            'checkAccess',
        );
    }

    /*
    public function actionCourse_payments()
    {
        $this->render('course_payments');
    }

    public function actionIndex()
    {
        $this->render('index');
    }
    */

    public function actionGetStudentDropList($course_type_id){
        $courses = Course::model()->with('students')->findAll('status in (:status) AND course_type_id = :course_type_id',array(
            ':status'=>implode(',',array(Course::STATUS_IN_PROGRESS,Course::STATUS_FINISHED)),
            ':course_type_id'=>$course_type_id,
        ));

        $this->renderPartial('partials/students_drop_list',array(
            'courses'=>$courses,
        ));

    }
    public function actionCreate(){
        $this->pageTitle = "نموذج ادخال الفواتير";
        $this->layout = "//layouts/column2";
        $message="";
        $lastPaymentReport = "";
        $payment = new Payment('create');

        $payment->num = 0;
        $payment->date = date('Y-m-d');
        if(isset($_POST['Payment'])){
            $payment->attributes = $_POST['Payment'];
            if(!empty($_POST['Payment']['student_course_id'])){
                $paymentIds = explode(',',$_POST['Payment']['student_course_id']);
                $payment->course_id = $paymentIds[0];
                $payment->student_id = $paymentIds[1];
            }

            if($payment->save()){
                //Build Report message
                $student = $this->loadStudentModel($payment->student_id);
                $name = $student->getName();
                $course = $this->loadCourseModel($payment->course_id);
                $payments = Payment::model()->findAll("student_id=:student_id AND course_id=:course_id", array(
                    ":student_id" => $student->id,
                    ":course_id" => $course->id,
                ));
                $courseCost = intval($course->getCostText());
                $paid = 0;
                foreach ($payments as $payment) {
                    $paid += $payment->amount;
                }
                $discount = intval($this->getStudentDiscount($payment->student_id, $payment->course_id));
                $remaining = $courseCost - $paid - $discount;
                $message .= "<p>تم اضافة الفاتورة بنجاح</p>";
                $message .= "<p>اسم الطالب: $name</p>";
                $message .= "<p>المدفوع: $paid</p>";
                $message .= "المتبقي للدفع: ".$remaining;
                // Unset the attribute to add a new Payment model
                $payment->unsetAttributes();
                $payment->num = 0;
                $payment->date = date('Y-m-d');
                $payment->isNewRecord = true;
            }
        }
        $this->render('create',array(
            'model'=>$payment,
            'message'=>$message,
            'lastPaymentReport'=>$lastPaymentReport,
        ));
    }

    public function actionPayments()
    {
        if (!$this->_student->isAttendingCourse($this->_course->id)) {
            $this->redirect(array('student/view', 'id' => $this->_student->id));
        }
        $this->layout = "//layouts/column2";
        $this->pageTitle = "سجل المدفوعات";
        $dataProvider = new CActiveDataProvider('Payment', array(
            'criteria' => array(
                'condition' => 'student_id=:student_id AND course_id=:course_id',
                'params' => array(
                    ':course_id' => $this->_course->id,
                    ':student_id' => $this->_student->id,
                ),
                //'order'=>'num ASC',
            ),
            'pagination' => array(
                'pageSize' => 10,
            ),
        ));
        $this->render('payments', array(
            'dataProvider' => $dataProvider,
        ));

    }

    public function actionPay()
    {
        if (isset($_POST['Payment'])) {
            $model = new Payment('create');
            $model->attributes = $_POST['Payment'];
            $model->date = date('Y-m-d');
            if ($model->num == 0) {
                $model->num = Payment::model()->getLastPaymentNo($_POST['Payment']['student_id'], $_POST['Payment']['course_id']) + 1;
            }
            if ($model->save()) {
                echo CJSON::encode(array('status' => 'success', 'message' => 'تم اضافة فاتورة جديدة'));
            } else {
                $form = new CActiveForm;
                echo CJSON::encode(array('status' => 'fail', 'message' => $form->errorSummary($model, 'رجاء اصلح الأخطاء التالية:')));
            }
        }
        Yii::app()->end();
    }

    public function actionBills()
    {
        $this->pageTitle = "إدارة فواتير المعهد";
        $this->layout = "//layouts/column2";
        $model = new Payment('search');
        $model->unsetAttributes();
        if (isset($_GET['Payment'])) {
            $model->attributes = $_GET['Payment'];
            $studentFirstName = $_GET['student_first_name'];
            $studentLastName = $_GET['student_last_name'];
            $criteria = new CDbCriteria;
            $criteria->compare('first_name', $studentFirstName, true);
            $criteria->compare('last_name', $studentLastName, true);
            $students = Student::model()->findAll($criteria);
            $student_array = array();
            foreach ($students as $student) {
                $student_array[] = $student->id;
            }
            $course_array = array();
            $course_type_id = intval($_GET['Payment']['course_id']);
            if (isset($course_type_id) && $course_type_id > 0) {
                foreach (CourseType::model()->findByPk($course_type_id)->courses as $course) {
                    $course_array[] = $course->id;
                }
            }
            $model->course_id = $course_array;
            $model->student_id = $student_array;
        }
        $this->render('bills', array(
            'paymentModel' => $model,
        ));
    }

    public function actionStudent_payments()
    {
        $this->render('student_payments');
    }

    public function actionAddDiscount()
    {
        $discount = $this->getStudentDiscount($this->_student->id, $this->_course->id);
        echo $this->renderPartial('partials/add_discount_form', array(
            'discount' => $discount,
            'student_id' => $this->_student->id,
            'course_id' => $this->_course->id,
        ), false, true);
        Yii::app()->end();
    }

    public function actionPostDiscount()
    {
        if (!isset($_POST['discount'])) {
            throw new CHttpException(400, 'خطأ في الإدخال');
        }
        $discount = $_POST['discount'];
        $course_id = $_POST['course_id'];
        $student_id = $_POST['student_id'];

        $course = $this->loadCourseModel($course_id);
        $student = $this->loadStudentModel($student_id);

        $payments = Payment::model()->findAll("student_id=:student_id AND course_id=:course_id", array(
            ":student_id" => $student->id,
            ":course_id" => $course->id,
        ));
        $courseCost = $course->cost;
        $paid = 0;
        foreach ($payments as $payment) {
            $paid += $payment->amount;
        }

        if ($discount < 0 || $discount > $courseCost - $paid) {
            echo CJSON::encode(array(
                'status' => false,
                'message' => 'الرقم المدخل قد يكون اكبر من اللازم او خاطئ',
            ));
            Yii::app()->end();
        } else {
            $command = Yii::app()->db->createCommand();
            $rowNum = $command->update('tbl_student_course_assignment', array(
                    'discount' => $discount
                ),
                'student_id=:student_id AND course_id=:course_id',
                array(
                    ':student_id' => $student->id,
                    ':course_id' => $course->id,
                ));
            if ($rowNum == 1) {
                echo CJSON::encode(array(
                    'status' => true,
                    'message' => 'تم اضافة حسم للطالب',
                ));
            } else {
                echo CJSON::encode(array(
                    'status' => false,
                    'message' => 'حدث خطأ في اعطاء حسم للطالب',
                ));
            }
            Yii::app()->end();
        }
    }

    public function actionGetPaymentForm($sId)
    {
        if (Yii::app()->request->isAjaxRequest) {
            if (!isset($_GET['ref'])) {
                throw new CHttpException(400);
            }
            $payment = new Payment;
            $student = $this->loadStudentModel($sId);
            $course = null;
            if (isset($_GET['cId'])) {
                $cId = $_GET['cId'];
                $course = $this->loadCourseModel($cId);
            } else if ($_GET['ref'] == "course_page") {
                throw new CHttpException(400);
            }
            $paymentInfo = array();
            $courseList = array();
            $payment->course_id = "";
            if ($_GET['ref'] == "course_page") {
                $payment->course_id = $cId;
                $payments = Payment::model()->findAll("student_id=:student_id AND course_id=:course_id", array(
                    ":student_id" => $student->id,
                    ":course_id" => $course->id,
                ));
                $courseCost = intval($course->getCostText());
                $paid = 0;
                foreach ($payments as $payment) {
                    $paid += $payment->amount;
                }

protected/views/payment/partials/add_discount_form.php
<?php
/**
 * Created by PhpStorm.
 * User: Dell 3521
 * Date: 04/07/14
 * Time: 07:54 م
 */
CommonFunctions::fixAjax();
echo CHtml::beginForm($this->createUrl("postDiscount"), 'post', array(
    'role' => 'form',
    'class' => 'form-horizontal',
));?>
    <div class="form-group">
        <?php echo CHtml::label("قيمة الخصم", 'discount', array('class' => 'col-md-3 control-label')); ?>
        <div class="col-md-9 input-container">
            <?php echo CHtml::textField("discount", $discount, array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
        </div>
    </div>
<?php echo CHtml::hiddenField('student_id', $student_id) ?>
<?php echo CHtml::hiddenField('course_id', $course_id) ?>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?php echo CHtml::ajaxSubmitButton('إضافة خصم', $this->createUrl('postDiscount'), array(
                'type' => 'POST',
                'dataType' => 'json',
                'success' => 'js:function(data){
                    if(data.status){
                        refreshPaymentInfo();
                    }else{
                        vex.defaultOptions.className = "vex-theme-plain";
                        vex.dialog.alert(data.message);
                    }
                }',
                'beforeSend' => 'js:function(){
        $("#addDiscountModal").modal("hide");
    }',
            ), array(
                'class' => 'btn btn-danger',
                'id' => 'link-' . uniqid(),
            ))?>
        </div>
    </div>
<?php echo CHtml::endForm(); ?>

protected/views/payment/partials/payment_options.php
<?php CommonFunctions::fixAjax(); ?>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <?php echo CHtml::ajaxLink('حذف الفاتورة', Yii::app()->createUrl('payment/deletePayment'), array(
                'type' => 'POST',
                'dataType' => 'json',
                'data' => array('YII_CSRF_TOKEN' => Yii::app()->request->csrfToken, 'id' => $payment->id,'extra_payment_options_token'=>isset($_GET['extra_payment_options_token'])?$_GET['extra_payment_options_token']:"payments"),
                'success' => 'js:function(data){
                    $("#paymentOptionsModal").modal("hide");
                    if(data.status){
                        if(data.ref=="bills"){
                            $("#bills-grid").yiiGridView("update");
                        }else{
                            refreshPaymentInfo();
                            $("#app_grid").yiiGridView("update");
                        }
                    }else{
                        vex.defaultOptions.className = "vex-theme-plain";
                        vex.dialog.alert(data.message);
                    }
                }'
            ),
            array(
                'class' => 'btn btn-danger btn-lg btn-block',
                'id' => 'link-' . uniqid(),
                'confirm' => 'هل تريد بالتأكيد حذف الفاتورة؟',
            ))?>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <?php echo CHtml::ajaxLink('تعديل بيانات فاتورة', Yii::app()->createUrl('payment/getUpdateForm', array('id' => $payment->id)), array(
                'type' => 'GET',
                'dataType' => 'html',
                'success' => 'js:function(data){
                    $("#paymentUpdateModal .modal-body").fadeOut(300,function(){
                        $("#paymentUpdateModal .modal-body").html(data);
                    });
                    $("#paymentUpdateModal .modal-body").fadeIn(500);
                }',
                'beforeSend' => 'js:function(xhr,setting){
                    $("#paymentOptionsModal").modal("hide");
                    $("#paymentUpdateModal .modal-body").hide();
                    $("#paymentUpdateModal").modal("show");
                    $("#paymentUpdateModal .modal-body").html("الرجاء الانتظار ...");
                    $("#paymentUpdateModal .modal-body").fadeIn(500);

                }'
            ),
            array(
                'class' => 'btn btn-success btn-lg btn-block',
                'id' => 'link-' . uniqid(),

            ))?>
    </div>
</div>
<br/>
<?php if (isset($_GET['extra_payment_options_token'])): ?>

    <hr style="border-bottom-color: #777777">
    <h5>خيارات اخرى</h5>
    <hr style="border-bottom-color: #777777">
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <?php echo CHtml::link("الذهاب الى صفحة الطالب الدافع للفاتورة",array('student/view','id'=>$payment->student_id),array(
                'class'=>'btn btn-success btn-block',
            ))?>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <?php echo CHtml::link("الذهاب الى صفحة الدورة التي دفعت فيها الفاتورة",array('course/view','id'=>$payment->course_id),array(
                'class'=>'btn btn-warning btn-block',
            ))?>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <?php echo CHtml::link("الذهاب الى مالية الطالب في الدورة",array('payment/payments','sId'=>$payment->student_id,'cId'=>$payment->course_id),array(
                'class'=>'btn btn-danger btn-block',
            ))?>
        </div>
    </div>
    <br/>
<?php endif; ?>

protected/views/payment/partials/payment_update.php
<?php
/* @var $this PaymentController */
/* @var $model Payment */
/* @var $form CActiveForm */
CommonFunctions::fixAjax();
Yii::app()->clientScript->registerScript("course_script", '
    $(".ok-sign").hide();
    $(".error-sign").hide();
', CClientScript::POS_END);
?>

<div class="form">

    <?php $form = $this->beginWidget('CActiveForm', array(
        'id' => 'payment-update-form',
        'enableAjaxValidation' => false,
        'enableClientValidation' => true,
        'focus' => array($model, 'amount'),
        'clientOptions' => array(
            'successCssClass' => 'has-success',
            'errorCssClass' => 'has-error',
            'validatingErrorMessage' => '',
            'inputContainer' => '.form-group',
            'afterValidateAttribute' => 'js:function(form, attribute, data, hasError){
                $("#"+attribute.inputID).siblings(".error-sign").hide();
                $("#"+attribute.inputID).siblings(".ok-sign").hide();
                if(hasError){
                    $("#"+attribute.inputID).siblings(".error-sign").show();
                }else {
                    $("#"+attribute.inputID).siblings(".ok-sign").show();
                }
            }',
        ),
        'htmlOptions' => array(
            'role' => 'form',
            'class' => 'form-horizontal',
        ),
    )); ?>

    <div class="hidden">
        <?php echo $form->hiddenField($model, 'student_id'); ?>
        <?php echo $form->hiddenField($model, 'course_id'); ?>
    </div>

    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'note', array('class' => 'col-md-4 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'note', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'note'); ?>
        </div>
    </div>

    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'num', array('class' => 'col-md-4 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'num', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'num'); ?>
        </div>
    </div>

    <div class="form-group has-feedback">
        <?php echo $form->labelEx($model, 'date', array('class' => 'col-md-4 control-label')); ?>
        <div class="col-md-6 input-container">
            <?php echo $form->textField($model, 'date', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
            <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
            <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            <?php echo $form->error($model, 'date'); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-6">
            <?php echo CHtml::ajaxSubmitButton('تعديل فاتورة', $this->createUrl('updatePayment', array('id' => $model->id)), array(
                'type' => 'POST',
                'dataType' => 'json',
                'success' => 'js:function(data){
                    vex.defaultOptions.className = "vex-theme-plain";
                    vex.dialog.alert(data.message);
                    if(data.status==true){
                        $("#app_grid").yiiGridView("update");
                        $("#bills-grid").yiiGridView("update");
                    }
                    $("#paymentUpdateModal").modal("hide");
                }',
                
            ), array(
                'class' => 'btn btn-danger',
                'id' => 'link-' . uniqid(),
            )); ?>
        </div>
    </div>


    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/payment/partials/search-form.php
<?php
/* @var $this PaymentController */
/* @var $model Payment */
/* @var $form CActiveForm */
?>
<br/>
<div class="panel panel-info search-form">
    <div class="panel-heading">البحث المتقدم في الفواتير</div>
    <div class="panel-body">
        <?php $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
            'htmlOptions'=>array(
                'role'=>'form',
                'class'=>'form-horizontal',
            ),
        )); ?>
        <div class="form-group has-feedback">
            <?php echo CHtml::label("الاسم الأول للطالب","", array('class' => 'col-md-3 control-label')); ?>
            <div class="col-md-9 input-container">
                <?php echo CHtml::textField("student_first_name","",array('size' => 60, 'maxlength' => 255, 'class' => 'form-control'));?></span>
                <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>

            </div>
        </div>
        <div class="form-group has-feedback">
            <?php echo CHtml::label("الاسم الاخير للطالب","", array('class' => 'col-md-3 control-label')); ?>
            <div class="col-md-9 input-container">
                <?php echo CHtml::textField("student_last_name","",array('size' => 60, 'maxlength' => 255, 'class' => 'form-control'));?></span>
                <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
            </div>
        </div>

        <div class="form-group has-feedback">
            <?php echo $form->labelEx($model, 'course_id', array('class' => 'col-md-3 control-label')); ?>
            <div class="col-md-9 input-container">
                <?php echo $form->dropDownList($model, 'course_id', CourseType::model()->getAvailableCourseTypes(), array('prompt' => 'اختر نوع الدورة', 'class' => 'form-control')); ?>
                <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
                <?php echo $form->error($model, 'course_id'); ?>
            </div>
        </div>


        <div class="form-group has-feedback">
            <?php echo $form->labelEx($model, 'num', array('class' => 'col-md-3 control-label')); ?>
            <div class="col-md-9 input-container">
                <?php echo $form->textField($model, 'num', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
                <?php echo $form->error($model, 'num'); ?>
            </div>
        </div>


        <div class="form-group has-feedback">
            <?php echo $form->labelEx($model, 'amount', array('class' => 'col-md-3 control-label')); ?>
            <div class="col-md-9 input-container">
                <?php echo $form->textField($model, 'amount', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
                <?php echo $form->error($model, 'amount'); ?>
            </div>
        </div>
        <div class="form-group has-feedback">
            <?php echo $form->labelEx($model, 'date', array('class' => 'col-md-3 control-label')); ?>
            <div class="col-md-9 input-container">
                <?php echo $form->textField($model, 'date', array('size' => 60, 'maxlength' => 255, 'class' => 'form-control')); ?>
                <span class="glyphicon glyphicon-remove form-control-feedback error-sign"></span>
                <span class="glyphicon glyphicon-ok form-control-feedback ok-sign"></span>
                <?php echo $form->error($model, 'date'); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <?php echo CHtml::submitButton('فلترة', array(
                    'class' => 'btn btn-success',
                )); ?>
            </div>
        </div>

        <?php $this->endWidget(); ?>

    </div>

</div><!-- search-form -->

protected/views/payment/partials/students_drop_list.php
<?php
/**
 * @var $courses Course[]
 *
 */

if(empty($courses)){
    echo "<option>لايوجد طلاب</option>";
}
if(!empty($courses)){
    
    echo "<option value=''>اختر طالب</option>";

    foreach($courses as $course){
        $courseId = $course->id;
        foreach($course->students as $student){
            $studentName = $student->getName();
            $studentId = $student->id;
            echo "<option value='$courseId,$studentId'>$studentName</option>";
        }
    }

}